{
 "title": "Crawler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "crawler_pages_parsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "crawler_site_connection_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum"
    }
   ]
  },
  {
   "title": "crawler_page_parse_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(crawler_page_parse_time_sum[$__rate_interval])"
    }
   ]
  },
  { "title": "Crawler-UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "web_pages_served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "web_pages_served" }
   ]
  },
  {
   "title": "web_page_gen_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(web_page_gen_time_sum[$__rate_interval])"
    }
   ]
  }
 ]
}