global:
  namespace: crawler

service:
  externalPort: 8000
  targetPort: 8000
  name: crawler-ui-service
  checkPath: /metrics

deployment:
  image: asazanoff/crawler-ui:main
  replicas: 1
  name: crawler-ui-app
  env:
    mongoAddress: mongodb.mongodb.svc.cluster.local
    mongoPort: 27017
    flaskApp: /ui.py

ingress:
    host: search.xn--e1adnf2fb.xn--p1ai