global:
    namespace: crawler

deployment:
    image: asazanoff/crawler:main
    name: crawler-deployment
    replicas: 1
    env:
        mongoAddress: mongodb.mongodb.svc.cluster.local
        mongoPort: 27017
        rabbitHost: rabbitmq.rabbit.svc.cluster.local
        rabbitQueue: 
        rabbitUser:
        rabbitPassword: 
        checkInterval: 25
        exclude: ".*github.com,.*twitter.com,.*githubstatus.com"
        url: "https://vitkhab.github.io/search_engine_test_site/"

service:
    externalPort: 8000
    targetPort: 8000
    name: crawler-service
    checkPath: /
