name: Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call: 
    inputs:
      crawler-ui-image:
          required: false
          type: string
          description: Image tag of crawler-ui
    secrets:
      KUBECONFIG:
        required: true

env:
  HELM_REPO_NAME: the-best-org/cicd

jobs:
  upgrade_crawler-ui:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.inputs.crawler-ui-image != '' }} && github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout helm repo
        uses: actions/checkout@v3
        with: 
          repository: ${{ env.HELM_REPO_NAME }}
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3.1.0
        with:
          exec: >
            helm upgrade crawler-ui ./crawler-ui/ --install --wait --atomic
            --namespace=crawler --values=./crawler-ui/values.yaml
            --set deployment.image=${{ github.event.inputs.crawler-ui-image }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          overrule_existing_kubeconfig: "true"
