name: Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call: 
    inputs:
      crawler-ui-image:
          required: false
          type: string
          description: Image tag of crawler-ui

# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: docker.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: asazanoff/crawler
#   USERNAME: asazanoff
#   TEST_TAG: test

jobs:
  upgrade_crawler:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: >
            helm upgrade crawler-ui ./crawler-ui/ --install --wait --atomic
            --namespace=crawler --values=./crawler-ui/values.yaml
            --set deployment.image=${{ inputs.crawler-ui-image }}
            --set ingress.host=${{ vars.SEARCH_INGRESS_ADDRESS }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
